import React, { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { useStorage, type InventoryItem, type InventoryHistory } from '../context/StorageContext';
import { Button } from '../components/Button';
import { Input } from '../components/Input';
import { ArrowLeft, Plus, Trash2, Package, Search, X, Calendar, User, Building, Tag, Hash, FileText, MinusCircle, PlusCircle, History, ChevronDown, ChevronUp, MapPin, CheckCircle, Download } from 'lucide-react';
import { generateId } from '../utils/id';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { useAuth } from '../context/AuthContext';

export const InventoryPage: React.FC = () => {
  const navigate = useNavigate();
  const { user } = useAuth();
  const { getInventoryItems, saveInventoryItem, deleteInventoryItem } = useStorage();
  
  const [items, setItems] = useState<InventoryItem[]>([]);
  const [showAddForm, setShowAddForm] = useState(false);
  const [searchQuery, setSearchQuery] = useState('');
  
  // Selection & Actions
  const [selectedItemId, setSelectedItemId] = useState<string | null>(null);
  const [showPullOutForm, setShowPullOutForm] = useState(false);
  const [showRefillForm, setShowRefillForm] = useState(false);
  const [showHistoryId, setShowHistoryId] = useState<string | null>(null);

  const handleExportPDF = () => {
    const doc = new jsPDF({ orientation: 'p', unit: 'mm', format: 'a4' });
    const margin = 15;
    
    doc.setFontSize(18);
    doc.setTextColor(0, 123, 255);
    doc.text('INVENTORY ASSET REPORT', margin, 20);
    
    doc.setFontSize(10);
    doc.setTextColor(100);
    doc.text(`Company: ${user?.profile?.company || 'N/A'}`, margin, 26);
    doc.text(`Generated by: ${user?.profile?.fullName || user?.name}`, margin, 31);
    doc.text(`Date: ${new Date().toLocaleString()}`, margin, 36);

    const tableData = filteredItems.map(item => [
      item.itemCode,
      item.name,
      item.model || '-',
      item.quantity.toString(),
      item.department,
      item.dateInventory
    ]);

    autoTable(doc, {
      startY: 45,
      margin: { left: margin, right: margin },
      head: [['Code', 'Item Name', 'Model', 'Qty', 'Department', 'Inv. Date']],
      body: tableData,
      theme: 'striped',
      headStyles: { fillColor: [0, 123, 255] },
      styles: { fontSize: 8, cellPadding: 3 }
    });

    doc.setFontSize(9);
    doc.setTextColor(150);
    doc.text(`Publisher: Engr. Ailes | FieldSnap Systems`, margin, doc.internal.pageSize.getHeight() - 10);
    
    doc.save(`Inventory_Report_${Date.now()}.pdf`);
  };

  // New Item Form state
  const [formData, setFormData] = useState({
    itemCode: '',
    name: '',
    model: '',
    quantity: '',
    dateInventory: new Date().toISOString().split('T')[0],
    requestedBy: '',
    department: '',
    remarks: ''
  });

  // Action Form states
  const [actionData, setActionData] = useState({
    quantity: '',
    person: '',
    department: '',
    location: '',
    approvedBy: ''
  });

  useEffect(() => {
    loadItems();
  }, []);

  const loadItems = async () => {
    const data = await getInventoryItems();
    // Ensure history exists for older items if any
    const migration = data.map(item => ({
      ...item,
      history: item.history || []
    }));
    setItems(migration);
  };

  const handleSaveNewItem = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!formData.itemCode || !formData.name || !formData.quantity) return;

    const newItem: Omit<InventoryItem, 'userId'> = {
      id: generateId(),
      itemCode: formData.itemCode,
      name: formData.name,
      model: formData.model,
      quantity: Number(formData.quantity),
      dateInventory: formData.dateInventory,
      requestedBy: formData.requestedBy,
      department: formData.department,
      remarks: formData.remarks,
      history: [],
      timestamp: Date.now()
    };

    await saveInventoryItem(newItem);
    setShowAddForm(false);
    resetNewItemForm();
    loadItems();
  };

  const resetNewItemForm = () => {
    setFormData({
      itemCode: '',
      name: '',
      model: '',
      quantity: '',
      dateInventory: new Date().toISOString().split('T')[0],
      requestedBy: '',
      department: '',
      remarks: ''
    });
  };

  const handleAction = async (type: 'Add' | 'Pull-out') => {
    if (!selectedItemId || !actionData.quantity || !actionData.person) return;
    
    const item = items.find(i => i.id === selectedItemId);
    if (!item) return;

    const qty = Number(actionData.quantity);
    if (type === 'Pull-out' && qty > item.quantity) {
      alert('Insufficient stock!');
      return;
    }

    const historyEntry: InventoryHistory = {
      id: generateId(),
      type,
      quantity: qty,
      person: actionData.person,
      department: actionData.department,
      location: actionData.location,
      approvedBy: actionData.approvedBy,
      timestamp: Date.now()
    };

    const updatedItem: InventoryItem = {
      ...item,
      quantity: type === 'Add' ? item.quantity + qty : item.quantity - qty,
      history: [historyEntry, ...(item.history || [])]
    };

    await saveInventoryItem(updatedItem);
    setShowPullOutForm(false);
    setShowRefillForm(false);
    setActionData({ quantity: '', person: '', department: '', location: '', approvedBy: '' });
    loadItems();
  };

  const handleDelete = async (e: React.MouseEvent, id: string) => {
    e.stopPropagation();
    if (window.confirm('Are you sure you want to delete this item?')) {
      await deleteInventoryItem(id);
      if (selectedItemId === id) setSelectedItemId(null);
      loadItems();
    }
  };

  const filteredItems = items.filter(item => 
    item.name.toLowerCase().includes(searchQuery.toLowerCase()) ||
    item.itemCode.toLowerCase().includes(searchQuery.toLowerCase()) ||
    item.department.toLowerCase().includes(searchQuery.toLowerCase())
  );

  const selectedItem = items.find(i => i.id === selectedItemId);

  return (
    <div className="container" style={{ paddingBottom: '5rem' }}>
      <header style={{ marginBottom: '1.5rem', marginTop: '1rem', display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: '1rem' }}>
          <button 
            onClick={() => navigate(-1)} 
            style={{ background: 'none', border: 'none', color: 'var(--text)', cursor: 'pointer', padding: '0.5rem' }}
          >
            <ArrowLeft size={24} />
          </button>
          <div>
            <h1 style={{ fontSize: '1.5rem', fontWeight: '700' }}>Inventory</h1>
            <p style={{ color: 'var(--text-secondary)', fontSize: '0.9rem' }}>Manage your items and stocks</p>
          </div>
        </div>
        <button 
          onClick={handleExportPDF}
          style={{ background: 'var(--surface)', border: '1px solid var(--border)', borderRadius: '12px', cursor: 'pointer', padding: '0.75rem', color: 'var(--text)' }}
          title="Export PDF"
        >
          <Download size={20} />
        </button>
      </header>

      {!showAddForm ? (
        <>
          <div style={{ display: 'flex', gap: '0.75rem', marginBottom: '1.5rem' }}>
            <div style={{ flex: 1, position: 'relative' }}>
              <Search size={18} style={{ position: 'absolute', left: '12px', top: '50%', transform: 'translateY(-50%)', color: 'var(--text-secondary)' }} />
              <input 
                type="text" 
                placeholder="Search items..." 
                className="input-field" 
                style={{ paddingLeft: '40px' }}
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
              />
            </div>
            <button 
              onClick={() => setShowAddForm(true)}
              style={{ padding: '0.85rem', borderRadius: '12px', background: 'var(--primary)', color: 'white', border: 'none', cursor: 'pointer', display: 'flex', alignItems: 'center', justifyContent: 'center' }}
            >
              <Plus size={24} />
            </button>
          </div>

          <div style={{ display: 'flex', flexDirection: 'column', gap: '1rem' }}>
            {filteredItems.length === 0 ? (
              <div style={{ textAlign: 'center', padding: '3rem 1rem', color: 'var(--text-secondary)' }}>
                <Package size={48} style={{ marginBottom: '1rem', opacity: 0.5 }} />
                <p>No items found in inventory.</p>
              </div>
            ) : (
              filteredItems.map(item => (
                <div 
                  key={item.id} 
                  className="card" 
                  onClick={() => setSelectedItemId(selectedItemId === item.id ? null : item.id)}
                  style={{ 
                    padding: '1rem', 
                    border: selectedItemId === item.id ? '2px solid var(--primary)' : '1px solid var(--border)',
                    position: 'relative'
                  }}
                >
                  <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: '0.75rem' }}>
                    <div style={{ display: 'flex', gap: '0.75rem', alignItems: 'center' }}>
                      <div style={{ width: '40px', height: '40px', borderRadius: '10px', background: 'rgba(0, 123, 255, 0.1)', color: 'var(--primary)', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
                        <Package size={20} />
                      </div>
                      <div>
                        <h3 style={{ fontSize: '1rem', fontWeight: '700' }}>{item.name}</h3>
                        <p style={{ fontSize: '0.8rem', color: 'var(--text-secondary)' }}>Code: {item.itemCode}</p>
                      </div>
                    </div>
                    <div style={{ display: 'flex', gap: '0.5rem' }}>
                       <button 
                        onClick={(e) => { e.stopPropagation(); setShowHistoryId(showHistoryId === item.id ? null : item.id); }}
                        style={{ background: 'none', border: 'none', color: 'var(--primary)', cursor: 'pointer', padding: '0.4rem' }}
                      >
                        <History size={18} />
                      </button>
                      <button 
                        onClick={(e) => handleDelete(e, item.id)}
                        style={{ background: 'none', border: 'none', color: 'var(--danger)', cursor: 'pointer', padding: '0.4rem' }}
                      >
                        <Trash2 size={18} />
                      </button>
                    </div>
                  </div>
                  
                  <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '0.75rem', fontSize: '0.85rem', color: 'var(--text-secondary)', background: 'var(--background)', padding: '0.75rem', borderRadius: '8px' }}>
                    <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
                      <Tag size={14} /> Qty: <span style={{ color: 'var(--text)', fontWeight: '600' }}>{item.quantity}</span>
                    </div>
                    <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
                      <Calendar size={14} /> {item.dateInventory}
                    </div>
                    <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
                      <Building size={14} /> {item.department}
                    </div>
                    <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
                      <User size={14} /> {item.requestedBy}
                    </div>
                  </div>

                  {showHistoryId === item.id && (
                    <div style={{ marginTop: '1rem', paddingTop: '1rem', borderTop: '1px solid var(--border)', animation: 'tabFadeIn 0.2s ease' }}>
                      <h4 style={{ fontSize: '0.85rem', marginBottom: '0.75rem', display: 'flex', alignItems: 'center', gap: '0.4rem' }}>
                        <History size={14} /> Transaction History
                      </h4>
                      {item.history && item.history.length > 0 ? (
                        <div style={{ display: 'flex', flexDirection: 'column', gap: '0.6rem' }}>
                          {item.history.map(h => (
                            <div key={h.id} style={{ fontSize: '0.75rem', padding: '0.6rem', background: 'var(--background)', borderRadius: '8px', borderLeft: `3px solid ${h.type === 'Add' ? 'var(--success)' : 'var(--danger)'}` }}>
                              <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: '0.25rem' }}>
                                <span style={{ fontWeight: 'bold', color: h.type === 'Add' ? 'var(--success)' : 'var(--danger)' }}>{h.type.toUpperCase()}</span>
                                <span style={{ opacity: 0.7 }}>{new Date(h.timestamp).toLocaleDateString()}</span>
                              </div>
                              <p>Qty: <strong>{h.quantity}</strong> | By: {h.person}</p>
                              {h.location && <p>Used at: {h.location}</p>}
                              {h.approvedBy && <p>Approved by: {h.approvedBy}</p>}
                            </div>
                          ))}
                        </div>
                      ) : (
                        <p style={{ fontSize: '0.75rem', opacity: 0.6 }}>No history available.</p>
                      )}
                    </div>
                  )}
                </div>
              ))
            )}
          </div>
        </>
      ) : (
        <form onSubmit={handleSaveNewItem} className="card" style={{ animation: 'tabFadeIn 0.3s ease' }}>
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '1.5rem' }}>
            <h3 style={{ fontSize: '1.25rem' }}>Add New Item</h3>
            <button onClick={() => setShowAddForm(false)} style={{ background: 'none', border: 'none', color: 'var(--text-secondary)', cursor: 'pointer' }}>
              <X size={24} />
            </button>
          </div>

          <div style={{ display: 'flex', flexDirection: 'column', gap: '1rem' }}>
            <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '1rem' }}>
              <Input 
                label="Item Code" 
                icon={<Hash size={18} />}
                value={formData.itemCode} 
                onChange={e => setFormData({...formData, itemCode: e.target.value})} 
                placeholder="e.g. ST-001"
                required
              />
              <Input 
                label="Quantity" 
                type="number"
                icon={<Tag size={18} />}
                value={formData.quantity} 
                onChange={e => setFormData({...formData, quantity: e.target.value})} 
                placeholder="0"
                required
              />
            </div>

            <Input 
              label="Item Name" 
              icon={<Package size={18} />}
              value={formData.name} 
              onChange={e => setFormData({...formData, name: e.target.value})} 
              placeholder="e.g. Concrete Mixer"
              required
            />

            <Input 
              label="Model (Optional)" 
              icon={<FileText size={18} />}
              value={formData.model} 
              onChange={e => setFormData({...formData, model: e.target.value})} 
              placeholder="e.g. Bosch Professional"
            />

            <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '1rem' }}>
              <Input 
                label="Inventory Date" 
                type="date"
                icon={<Calendar size={18} />}
                value={formData.dateInventory} 
                onChange={e => setFormData({...formData, dateInventory: e.target.value})} 
                required
              />
              <Input 
                label="Department" 
                icon={<Building size={18} />}
                value={formData.department} 
                onChange={e => setFormData({...formData, department: e.target.value})} 
                placeholder="e.g. Civil Works"
                required
              />
            </div>

            <Input 
              label="Requested By" 
              icon={<User size={18} />}
              value={formData.requestedBy} 
              onChange={e => setFormData({...formData, requestedBy: e.target.value})} 
              placeholder="Name of requester"
              required
            />

            <div className="input-group">
              <label className="input-label">Remarks/Details</label>
              <textarea 
                className="input-field" 
                style={{ resize: 'none', height: '100px', fontFamily: 'inherit' }}
                value={formData.remarks}
                onChange={e => setFormData({...formData, remarks: e.target.value})}
                placeholder="Enter any additional details..."
              ></textarea>
            </div>

            <div style={{ display: 'flex', gap: '1rem', marginTop: '1rem' }}>
              <button type="button" className="btn btn-secondary" onClick={() => setShowAddForm(false)} style={{ flex: 1 }}>Cancel</button>
              <button type="submit" className="btn btn-primary" style={{ flex: 2 }}>Save Item</button>
            </div>
          </div>
        </form>
      )}

      {/* Action Bar (Sticky at bottom when item selected) */}
      {selectedItemId && !showAddForm && !showPullOutForm && !showRefillForm && (
        <div style={{ position: 'fixed', bottom: '20px', left: '50%', transform: 'translateX(-50%)', width: 'calc(100% - 2rem)', maxWidth: '568px', background: 'var(--surface)', padding: '1rem', borderRadius: '16px', boxShadow: '0 8px 32px rgba(0,0,0,0.2)', border: '1px solid var(--border)', display: 'flex', gap: '0.75rem', zIndex: 100, animation: 'tabFadeIn 0.3s ease' }}>
          <button 
            onClick={() => setShowRefillForm(true)}
            style={{ flex: 1, padding: '0.85rem', borderRadius: '12px', background: 'var(--success)', color: 'white', border: 'none', fontWeight: 'bold', display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '0.5rem', cursor: 'pointer' }}
          >
            <PlusCircle size={20} /> Add
          </button>
          <button 
            onClick={() => setShowPullOutForm(true)}
            style={{ flex: 1, padding: '0.85rem', borderRadius: '12px', background: 'var(--danger)', color: 'white', border: 'none', fontWeight: 'bold', display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '0.5rem', cursor: 'pointer' }}
          >
            <MinusCircle size={20} /> Pull-out
          </button>
        </div>
      )}

      {/* Modal Overlays */}
      {(showPullOutForm || showRefillForm) && (
        <div style={{ position: 'fixed', top: 0, left: 0, right: 0, bottom: 0, background: 'rgba(0,0,0,0.5)', display: 'flex', alignItems: 'center', justifyContent: 'center', padding: '1rem', zIndex: 1000 }}>
          <div className="card" style={{ width: '100%', maxWidth: '400px', margin: 0, animation: 'tabFadeIn 0.2s ease' }}>
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '1.5rem' }}>
              <h3 style={{ fontSize: '1.1rem', display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
                {showRefillForm ? <PlusCircle color="var(--success)" /> : <MinusCircle color="var(--danger)" />}
                {showRefillForm ? 'Add Stock' : 'Pull-out Stock'}
              </h3>
              <button onClick={() => { setShowPullOutForm(false); setShowRefillForm(false); }} style={{ background: 'none', border: 'none', color: 'var(--text-secondary)', cursor: 'pointer' }}>
                <X size={20} />
              </button>
            </div>

            <p style={{ fontSize: '0.9rem', marginBottom: '1rem', color: 'var(--text-secondary)' }}>
              Item: <strong style={{ color: 'var(--text)' }}>{selectedItem?.name}</strong> (Stock: {selectedItem?.quantity})
            </p>

            <div style={{ display: 'flex', flexDirection: 'column', gap: '0.75rem' }}>
              <Input 
                label="Quantity" 
                type="number"
                icon={<Tag size={16} />}
                value={actionData.quantity}
                onChange={e => setActionData({...actionData, quantity: e.target.value})}
                placeholder="Enter amount"
                required
              />
              <Input 
                label={showRefillForm ? "Added By" : "Requested By"} 
                icon={<User size={16} />}
                value={actionData.person}
                onChange={e => setActionData({...actionData, person: e.target.value})}
                placeholder="Enter name"
                required
              />
              <Input 
                label="Department" 
                icon={<Building size={16} />}
                value={actionData.department}
                onChange={e => setActionData({...actionData, department: e.target.value})}
                placeholder="Enter department"
                required
              />
              {showPullOutForm && (
                <>
                  <Input 
                    label="Where to use (Location)" 
                    icon={<MapPin size={16} />}
                    value={actionData.location}
                    onChange={e => setActionData({...actionData, location: e.target.value})}
                    placeholder="Enter site location"
                    required
                  />
                  <Input 
                    label="Approved By" 
                    icon={<CheckCircle size={16} />}
                    value={actionData.approvedBy}
                    onChange={e => setActionData({...actionData, approvedBy: e.target.value})}
                    placeholder="Approver name"
                    required
                  />
                </>
              )}
              
              <div style={{ display: 'flex', gap: '0.75rem', marginTop: '0.75rem' }}>
                <button 
                  type="button" 
                  className="btn btn-secondary" 
                  onClick={() => { setShowPullOutForm(false); setShowRefillForm(false); }}
                  style={{ flex: 1 }}
                >
                  Cancel
                </button>
                <button 
                  type="button" 
                  className="btn btn-primary" 
                  onClick={() => handleAction(showRefillForm ? 'Add' : 'Pull-out')}
                  style={{ flex: 1, background: showRefillForm ? 'var(--success)' : 'var(--danger)' }}
                >
                  Confirm
                </button>
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};
