import React, { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { useStorage, type MonitoringItem, type MonitoringChecklist, type MonitoringDailyStatus } from '../context/StorageContext';
import { useAuth } from '../context/AuthContext';
import { Button } from '../components/Button';
import { Input } from '../components/Input';
import { ArrowLeft, Plus, Trash2, Activity, MapPin, User, FileText, X, CheckCircle, XCircle, Search, Hash, Download, Save, History, Calendar } from 'lucide-react';
import { generateId } from '../utils/id';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

export const MonitoringPage: React.FC = () => {
  const navigate = useNavigate();
  const { user } = useAuth();
  const { getMonitoringItems, saveMonitoringItem, deleteMonitoringItem, getMonitoringChecklists, saveMonitoringDailyStatus, getAllMonitoringDailyStatus } = useStorage();
  
  const [items, setItems] = useState<MonitoringItem[]>([]);
  const [dailyStatuses, setDailyStatuses] = useState<Record<string, MonitoringDailyStatus>>({});
  const [showAddForm, setShowAddForm] = useState(false);
  const [searchQuery, setSearchQuery] = useState('');
  
  const [selectedDate, setSelectedDate] = useState(new Date().toISOString().split('T')[0]);
  const [showHistory, setShowHistory] = useState(false);
  const [historyDates, setHistoryDates] = useState<string[]>([]);

  const [formData, setFormData] = useState({
    code: '',
    equipmentName: '',
    location: '',
    status: 'Operational' as 'Operational' | 'Not Operational',
    monitoredBy: user?.profile?.fullName || user?.name || '',
    remarks: ''
  });

  useEffect(() => {
    loadItems();
  }, [selectedDate]);

  const loadItems = async () => {
    const equipment = await getMonitoringItems();
    setItems(equipment);

    // Get daily statuses for selected date
    const statuses = await getAllMonitoringDailyStatus(selectedDate);
    const statusMap: Record<string, MonitoringDailyStatus> = {};
    statuses.forEach(s => {
      statusMap[s.monitoringId] = s;
    });
    setDailyStatuses(statusMap);

    // Get unique dates for history
    // Since we don't have a direct "getAllDates" we could fetch all logs, but for now let's just use what we have
    // Realistically we'd fetch unique dates from the daily_status store
  };

  const handleUpdateStatus = async (itemId: string, currentStatus: 'Operational' | 'Not Operational') => {
    const newStatus = currentStatus === 'Operational' ? 'Not Operational' : 'Operational';
    const existing = dailyStatuses[itemId];
    
    const dailyUpdate: Omit<MonitoringDailyStatus, 'userId'> = {
      id: existing?.id || generateId(),
      monitoringId: itemId,
      date: selectedDate,
      status: newStatus,
      monitoredBy: existing?.monitoredBy || user?.profile?.fullName || user?.name || '',
      remarks: existing?.remarks || '',
      timestamp: Date.now()
    };

    await saveMonitoringDailyStatus(dailyUpdate);
    loadItems();
  };

  const handleSaveDay = async () => {
    // In our current implementation, items are saved individually when updated.
    // This button can serve as a "Finalize" or just a confirmation.
    alert(`Monitoring records for ${selectedDate} have been updated and saved.`);
  };

  const handleExportAllPDF = async () => {
    if (items.length === 0) {
      alert("No equipment data to export.");
      return;
    }

    const doc = new jsPDF();
    const margin = 15;
    const pageWidth = doc.internal.pageSize.getWidth();
    
    doc.setFontSize(18);
    doc.setTextColor(0, 123, 255);
    doc.text('FACILITY MONITORING MASTER REPORT', pageWidth / 2, 20, { align: 'center' });
    
    doc.setFontSize(10);
    doc.setTextColor(100);
    doc.text(`Company: ${user?.profile?.company || 'N/A'}`, margin, 30);
    doc.text(`Generated by: ${user?.profile?.fullName || user?.name}`, margin, 35);
    doc.text(`Monitoring Date: ${selectedDate}`, margin, 40);

    let currentY = 50;

    for (const item of items) {
      if (currentY > 240) {
        doc.addPage();
        currentY = 20;
      }

      const daily = dailyStatuses[item.id];
      const status = daily?.status || item.status;

      doc.setFontSize(12);
      doc.setTextColor(0, 0, 0);
      doc.setFont('helvetica', 'bold');
      doc.text(`${item.equipmentName} (${item.code})`, margin, currentY);
      currentY += 6;

      doc.setFontSize(9);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(100);
      doc.text(`Location: ${item.location} | Status: ${status}`, margin, currentY);
      currentY += 8;

      const checklists = await getMonitoringChecklists(item.id);
      const dayChecklists = checklists.filter(c => c.date === selectedDate);
      
      const tableData = dayChecklists.map(c => [
        c.details,
        c.status,
        c.checkedBy,
        c.remarks || '-'
      ]);

      autoTable(doc, {
        startY: currentY,
        margin: { left: margin, right: margin },
        head: [['Inspection Details', 'Status', 'Checked By', 'Remarks']],
        body: tableData.length > 0 ? tableData : [['No inspection records for this date', '-', '-', '-']],
        theme: 'striped',
        headStyles: { fillColor: status === 'Operational' ? [40, 167, 69] : [220, 53, 69] },
        styles: { fontSize: 8, cellPadding: 2 }
      });
      
      currentY = (doc as any).lastAutoTable.finalY + 12;
    }

    doc.setFontSize(8);
    doc.setTextColor(150);
    doc.text('Generated via FieldSnap Systems', pageWidth / 2, doc.internal.pageSize.getHeight() - 10, { align: 'center' });

    doc.save(`Master_Monitoring_Report_${selectedDate}.pdf`);
  };

  const handleSubmitNewEquipment = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!formData.code || !formData.equipmentName) return;

    const itemId = generateId();
    await saveMonitoringItem({
      id: itemId,
      code: formData.code,
      equipmentName: formData.equipmentName,
      location: formData.location,
      status: formData.status,
      monitoredBy: formData.monitoredBy,
      remarks: formData.remarks,
      timestamp: Date.now()
    });

    // Also create initial daily log
    await saveMonitoringDailyStatus({
      id: generateId(),
      monitoringId: itemId,
      date: selectedDate,
      status: formData.status,
      monitoredBy: formData.monitoredBy,
      remarks: formData.remarks,
      timestamp: Date.now()
    });

    setFormData({
      code: '',
      equipmentName: '',
      location: '',
      status: 'Operational',
      monitoredBy: user?.profile?.fullName || user?.name || '',
      remarks: ''
    });
    setShowAddForm(false);
    loadItems();
  };

  const filteredItems = items.filter(item => 
    item.equipmentName.toLowerCase().includes(searchQuery.toLowerCase()) ||
    item.code.toLowerCase().includes(searchQuery.toLowerCase()) ||
    item.location.toLowerCase().includes(searchQuery.toLowerCase())
  );

  return (
    <div className="container" style={{ paddingBottom: '2rem' }}>
      <header style={{ marginBottom: '1.5rem', marginTop: '1rem', display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
        <button 
          onClick={() => navigate('/')} 
          style={{ background: 'none', border: 'none', color: 'var(--text)', cursor: 'pointer', padding: '0.5rem' }}
        >
          <ArrowLeft size={24} />
        </button>
        <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
          <button 
            onClick={() => setShowHistory(!showHistory)}
            style={{ background: 'var(--surface)', border: '1px solid var(--border)', borderRadius: '10px', padding: '0.6rem', color: 'var(--text)', cursor: 'pointer' }}
            title="History"
          >
            <History size={20} />
          </button>
          <button 
            onClick={handleSaveDay}
            style={{ background: 'var(--success)', border: 'none', borderRadius: '10px', padding: '0.6rem', color: 'white', cursor: 'pointer' }}
            title="Save for the Day"
          >
            <Save size={20} />
          </button>
          <button 
            onClick={handleExportAllPDF}
            style={{ background: 'var(--surface)', border: '1px solid var(--border)', borderRadius: '10px', padding: '0.6rem', color: 'var(--primary)', cursor: 'pointer' }}
            title="Export Master Report"
          >
            <Download size={20} />
          </button>
        </div>
      </header>

      <div style={{ marginBottom: '1.5rem' }}>
        <h1 style={{ fontSize: '1.5rem', fontWeight: '700' }}>Equipment Monitoring</h1>
        <p style={{ color: 'var(--text-secondary)', fontSize: '0.9rem' }}>Date: <strong>{selectedDate}</strong></p>
      </div>

      {showHistory && (
        <div className="card" style={{ marginBottom: '1.5rem', animation: 'tabFadeIn 0.2s ease', border: '1px solid var(--primary)' }}>
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '1rem' }}>
            <h3 style={{ fontSize: '0.9rem', fontWeight: 'bold' }}>View Past Monitoring</h3>
            <button onClick={() => setShowHistory(false)} style={{ background: 'none', border: 'none', color: 'var(--text-secondary)' }}><X size={18} /></button>
          </div>
          <input 
            type="date" 
            className="input-field" 
            value={selectedDate} 
            onChange={(e) => setSelectedDate(e.target.value)} 
          />
          <p style={{ fontSize: '0.7rem', marginTop: '0.5rem', opacity: 0.7 }}>Selecting a date will show the equipment status recorded on that specific day.</p>
        </div>
      )}

      {!showAddForm ? (
        <>
          <div style={{ display: 'flex', gap: '0.75rem', marginBottom: '1.5rem' }}>
            <div style={{ flex: 1, position: 'relative' }}>
              <Search size={18} style={{ position: 'absolute', left: '12px', top: '50%', transform: 'translateY(-50%)', color: 'var(--text-secondary)' }} />
              <input 
                type="text" 
                placeholder="Search equipment..." 
                className="input-field" 
                style={{ paddingLeft: '40px' }}
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
              />
            </div>
            <button 
              onClick={() => setShowAddForm(true)}
              style={{ padding: '0.85rem', borderRadius: '12px', background: 'var(--primary)', color: 'white', border: 'none', cursor: 'pointer', display: 'flex', alignItems: 'center', justifyContent: 'center' }}
            >
              <Plus size={24} />
            </button>
          </div>

          <div style={{ display: 'flex', flexDirection: 'column', gap: '1rem' }}>
            {filteredItems.length === 0 ? (
              <div style={{ textAlign: 'center', padding: '3rem 1rem', color: 'var(--text-secondary)', background: 'var(--surface)', borderRadius: '12px' }}>
                <Activity size={48} style={{ marginBottom: '1rem', opacity: 0.5 }} />
                <p>No equipment monitored yet.</p>
              </div>
            ) : (
              filteredItems.map(item => {
                const daily = dailyStatuses[item.id];
                const status = daily?.status || item.status;
                const monitoredBy = daily?.monitoredBy || item.monitoredBy;
                
                return (
                  <div 
                    key={item.id} 
                    className="card" 
                    onClick={() => navigate(`/monitoring-checklist/${item.id}`)}
                    style={{ padding: '1rem', cursor: 'pointer', borderLeft: `6px solid ${status === 'Operational' ? 'var(--success)' : 'var(--danger)'}` }}
                  >
                    <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: '0.75rem' }}>
                      <div style={{ display: 'flex', gap: '0.75rem', alignItems: 'center' }}>
                        <div style={{ width: '40px', height: '40px', borderRadius: '10px', background: 'rgba(0, 123, 255, 0.1)', color: 'var(--primary)', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
                          <Activity size={20} />
                        </div>
                        <div>
                          <h3 style={{ fontSize: '1rem', fontWeight: '700' }}>{item.equipmentName}</h3>
                          <p style={{ fontSize: '0.8rem', color: 'var(--text-secondary)' }}>Code: {item.code}</p>
                        </div>
                      </div>
                      <div style={{ display: 'flex', gap: '0.5rem' }}>
                        <button 
                          onClick={(e) => { e.stopPropagation(); handleUpdateStatus(item.id, status); }}
                          style={{ background: 'none', border: 'none', color: status === 'Operational' ? 'var(--success)' : 'var(--danger)', cursor: 'pointer', padding: '0.4rem' }}
                          title="Toggle Status"
                        >
                          {status === 'Operational' ? <CheckCircle size={20} /> : <XCircle size={20} />}
                        </button>
                        <button 
                          onClick={(e) => { e.stopPropagation(); if(window.confirm('Delete equipment?')) deleteMonitoringItem(item.id).then(loadItems); }}
                          style={{ background: 'none', border: 'none', color: 'var(--danger)', cursor: 'pointer', padding: '0.4rem' }}
                        >
                          <Trash2 size={18} />
                        </button>
                      </div>
                    </div>
                    
                    <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '0.75rem', fontSize: '0.85rem', color: 'var(--text-secondary)', background: 'var(--background)', padding: '0.75rem', borderRadius: '8px' }}>
                      <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
                        <MapPin size={14} /> {item.location}
                      </div>
                      <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', color: status === 'Operational' ? 'var(--success)' : 'var(--danger)', fontWeight: 'bold' }}>
                        {status}
                      </div>
                      <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', gridColumn: 'span 2' }}>
                        <User size={14} /> Monitored by: <span style={{ color: 'var(--text)' }}>{monitoredBy}</span>
                      </div>
                    </div>
                  </div>
                );
              })
            )}
          </div>
        </>
      ) : (
        <form onSubmit={handleSubmitNewEquipment} className="card" style={{ animation: 'tabFadeIn 0.3s ease' }}>
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '1.5rem' }}>
            <h3 style={{ fontSize: '1.25rem' }}>Add Equipment</h3>
            <button onClick={() => setShowAddForm(false)} style={{ background: 'none', border: 'none', color: 'var(--text-secondary)', cursor: 'pointer' }}>
              <X size={24} />
            </button>
          </div>

          <div style={{ display: 'flex', flexDirection: 'column', gap: '1rem' }}>
            <Input 
              label="Monitoring Code" 
              icon={<Hash size={18} />}
              value={formData.code} 
              onChange={e => setFormData({...formData, code: e.target.value})} 
              placeholder="e.g. HVAC-001"
              required
            />
            <Input 
              label="Equipment Name" 
              icon={<Activity size={18} />}
              value={formData.equipmentName} 
              onChange={e => setFormData({...formData, equipmentName: e.target.value})} 
              placeholder="e.g. Main Chiller Unit"
              required
            />
            <Input 
              label="Location" 
              icon={<MapPin size={18} />}
              value={formData.location} 
              onChange={e => setFormData({...formData, location: e.target.value})} 
              placeholder="e.g. Rooftop, East Wing"
              required
            />
            
            <div className="input-group">
              <label className="input-label">Current Status</label>
              <div style={{ display: 'flex', gap: '0.5rem' }}>
                {(['Operational', 'Not Operational'] as const).map(s => (
                  <button
                    key={s}
                    type="button"
                    onClick={() => setFormData({...formData, status: s})}
                    style={{ 
                      flex: 1, padding: '0.75rem', borderRadius: '12px', border: '1px solid var(--border)',
                      background: formData.status === s ? (s === 'Operational' ? 'var(--success)' : 'var(--danger)') : 'var(--surface)',
                      color: formData.status === s ? 'white' : 'var(--text)',
                      fontWeight: 'bold', cursor: 'pointer'
                    }}
                  >
                    {s}
                  </button>
                ))}
              </div>
            </div>

            <Input 
              label="Monitored By" 
              icon={<User size={18} />}
              value={formData.monitoredBy} 
              onChange={e => setFormData({...formData, monitoredBy: e.target.value})} 
              placeholder="Name of inspector"
              required
            />

            <div className="input-group">
              <label className="input-label">Initial Remarks</label>
              <textarea 
                className="input-field" 
                style={{ minHeight: '80px', resize: 'none', fontFamily: 'inherit' }}
                value={formData.remarks}
                onChange={e => setFormData({...formData, remarks: e.target.value})}
                placeholder="Any initial observations..."
              ></textarea>
            </div>

            <div style={{ display: 'flex', gap: '1rem', marginTop: '1rem' }}>
              <button type="button" className="btn btn-secondary" onClick={() => setShowAddForm(false)} style={{ flex: 1 }}>Cancel</button>
              <button type="submit" className="btn btn-primary" style={{ flex: 2 }}>Save Equipment</button>
            </div>
          </div>
        </form>
      )}
    </div>
  );
};
